- 24-04-06-MockCodingTest/2024-04-05-kakaoWinterIntership.txt
- 24-04-06-MockCodingTest/24-04-06-MockCodingTest.md
> April 1st week

- 24-04-13-MockCodingTest/24-04-13-MockCodingTest.md
> [PGS] {문제 이름 키패드 누르기, 주사위 고르기}

- 24-04-06-MockCodingTest/병헌/0406/도넛과_막대_그래프.java
1. 📑 사용한 알고리즘
- 그래프 탐색
연결리스트를 구현하기 위해 Class 객체를 만들어 Graph를 만들어주었습니다.   
해당 Class에서는 연결리스트를 구성하고, 정점 사이의 관계를 정의해줄 수 있는 함수를 작성하였습니다. 어떤 한 정점으로부터 나아가는 정점을 List 형식으로 받도록 정의하였습니다.    
문제를 풀던 중 정점으로 들어오는 간선의 개수와 나가는 간선의 개수가 영향이 있다는 점을 알고 해당 부분을 추적하기 위해 innerTrace와 outerTrace 배열을 만들어주었습니다. 각 배열은 해당 index 번호를 가진 정점으로 들어오는 간선의 개수와 나가는 간선의 개수를 추적합니다. 
- 나가는 간선만 있고 들어오는 간선이 없는 정점의 경우 새로 추가된 정점입니다.
- 나가는 간선의 개수가 2개이고 들어오는 간선의 개수가 하나 이상일 경우 도넛 모양의 그래프입니다.
- 들어오는 간선의 개수가 1개 이상이지만 나가는 간선이 없는 경우 막대 모양의 그래프입니다.
- 새로 생긴 정점에서 연결되서 만들어지는 전체 그래프의 개수에서 2, 3번에서 구한 값을 뺀다면 도넛 그래프의 개수를 구할 수 있습니다. 
풀지 못했읍니다..
1. 📑 사용한 알고리즘
5. 📑 구현 방식에 대한 간략한 설명
> 0406 알고리즘 스터디

- 24-06-3주차/병헌/BOJ_30804_과일 탕후루.java
1. 📑 사용한 알고리즘
Two pointer
- Hashmap과 Deque을 이용한 풀이방법을 시도해봤지만 반례가 발생하여 Two pointer 방식으로 풀이
- bruteforce 방식으로 left, right를 0번 index부터 시작하여 right가 최대 N에 도달할 때까지 pointer를 움직이며 각 구간 별 max length를 계산하였습니다. 
- 세부 조건은 과일의 종류가 2개 초과일 경우 left를 움직이고 그 외의 경우는 right를 움직이며 추적하였고, 9개 과일 크기만큼의 배열을 만들어 해당 과일들이 몇 개가 포함되어있는지를 추적하였습니다.
> [BOJ] 과일 탕후루

- 24-06-3주차/규현/BOJ_28437_막대_만들기.java
1. 📑 사용한 알고리즘
DP, 배수 찾기
주어진 막대 A... 들이 있고
목표 길이 L .... 이 있습니다.
주어진 막대 A의 배수를 통해 L을 만들 수 있는 경우의 수를 구하는 문제입니다.
처음엔 단순하게 A의 배수에 해당하는 L을 ++ 을 해주려고 했습니다. 그런데 배수를 만드는 순서도 중요한 문제였습니다.
ex) 1 * 2 * 3 하고 1 * 3 * 2가 다른 경우입니다
그래서 L을 기준으로 값을 더해주려고 했었는데, 이게 틀렸었습니다
문제를 푸는 과정에서 A에 배수를 먹이는 과정에서 L에 속해야만 배수를 제공할 수 있는 줄 알았는데, 그렇지는 않았습니다. 이 부분을 착각해서 상당히 많이 틀렸었는데, 박이언씨 반례를 보고 깨달음을 얻어서, 그 이후에는 쉽게 풀 수 있었습니다.
코드 자체가 어렵지는 않아서 쉽게 이해가능합니다..
> 백준_28437_막대만들기

- 24-07-1주차/규현/15486_퇴사2.java
1. 📑 사용한 알고리즘
DP
이 전 골드5 DP 문제를 포기하며 눈물을 흘리면서 복수를 다짐한 문제입니다.
퇴사를 하기 전에 최대한 많은 일을 처리하면서 돈을 땡기는 것이 포인트입니다.
각 날짜 별로 소요 시간 T와 얻을 수 있는 돈 P가 주어집니다.
이걸 보고 처음엔 냅색이라고 생각했는데, 약간 냅색은 아니고 명칭은 잘 모르겠는데 폴짝폴짝 뛰면서 제일 많은 가치를 가져가는 문제? 그런 느낌이라고 생각했습니다.
그래서 현재 날짜에서 진료를 한 경우와 그냥 진료 안하고 넘어가는 경우를 max 값으로 지정해줬습니다.
오늘 진료를 하지 않은 경우를 내일의 값과 비교해서 더 큰 값을 저장해주고 `  dp[i + 1] = Math.max(dp[i + 1], dp[i]);`
오늘 진료를 할 수 있다면, 하고 그 다음 날짜에 기록된 값과 비교해서 더 큰 값을 저장해주는 코드를 작성해주었습니다.
```java
if (i + cost <= n) {
dp[i + cost] = Math.max(dp[i + cost], dp[i] + value);
}
``` 
문제에서 말하는 cost의 의미를 조금 헷갈리고, 오늘 진료를 안하고 넘어가는 케이스를 필기는 했는데 구현을 하지 않아서 한번 틀렸네요.
주의해야겠습니다..
> 백준_15486 퇴사2  아~ 퇴사하고싶다

- 24-07-1주차/민우/Boj_5021_왕위계승.java
1. 📑 사용한 알고리즘
위상정렬, 해시맵
단방향 그래프이고, 피를 계승하는 순서가 중요하기 때문에 위상정렬을 통해 순서배치를 하는게 중요합니다.
key가 String이고 value가 String Array로 되어있는 단방향 그래프를 구현하는데 좀 코드가 더러워졌지만 위상 정렬 후 본인의 혈통 
끼리 비교하면 되는 문제입니다.
> [BOJ] 5021_왕위계승

- 24-07-1주차/경향/q1074_Z.java
- 24-07-1주차/경향/q1389_케빈베이컨의6단계법칙.java
1. 📑 사용한 알고리즘
- 분할 정복, 재귀
(r, c)의 위치를 판단
1. 해당 분면에 위치하는 경우, 순서 계산
2. 다른 분면에 위치하는 경우, 해당 분면 생략 후 다음 분면으로
- 1분면: (0, 0)
- 2분면: (0, 2^(N-1))
- 3분면: (2^(N-1), 0)
- 4분면: (2^(N-1), 2^(N-1))
> [BOJ] Z, 케빈 베이컨의 6단계 법칙

- 영욱/BJ_G4_5639_이진검색트리.java
1. 📑 사용한 알고리즘
트리 탐색, BFS
노드, 트리 클래스 만든다.
트리는 루트만 갖고 있어도 될듯
넣을 때 루트가 null이면 그냥 넣고 아니라면 넣을 자리를 찾는다.( 중위 순회한 값을 입력으로 주니까 이렇게 해도 될듯 )
넣을 값이 루트보다 작으면 왼쪽을 탐색하기 위해 Queue에 넣는다.
크면 오른쪽을 Queue에 넣는다.
now의 왼쪽이나 오른쪽이 null값일 까지 진행
후위 탐색은 간단하게 재귀로 구현( 왼쪽 끝까지 재귀로 가고 오른쪽 끝까지 재귀로 간 다음 마지막에 출력하면 됨)
입력의 길이나 끝을 몰라서 입력은 인터넷을 참고하였다.
> [BOJ] 5693이진검색트리

- 영욱/BJ_G3_1865_웜홀.java
- 영욱/BJ_G4_11404_플로이드.java
1. 📑 사용한 알고리즘
벨만포드
출발 노드가 정해지지 않아서 두 가지 방식이 있었습니다.
- 모든 노드를 출발 지점으로 삼고 모든 노드에 대하여 벨만-포드 알고리즘을 적용한다.( N만큼 시간이 더 걸릴 수 있다 )
- 벨만-포드는 최단 거리 배열(dist) 값이 INF값이라면 탐색하지 않는 조건문이 있는데( 시간이 단축된다 )
이를 해제하고 음수 사이클만 찾는다( 최단 거리는 보장X )
벨만-포드가 처음이고 공부가 목적이기 때문에 정공법인 1번 방법으로 풀었습니다.
도로는 양방향, 웜홀은 단방향 음수로 간선을 만든 후, 
시작 노드를 반복문을 사용하여 모든 노드를 넘겨주었습니다.
벨만-포드의 핵심은 최단 거리에 필요한 간선은 N(노드 수)-1이며, 
이 이상일 경우 음수 사이클이 있다라고 판단한다 입니다.
그래서 N-1번만큼 모든 간선을 돌며 최단 거리 배열을 갱신하고, 
N-1번을 돌았는데도 최단 거리가 갱신된다면 다시 한번 더 모든 간선을 탐색,갱신하고
만약 최단 거리 배열이 갱신된다면 음수 사이클이 있다고 판단하는 문제였습니다
1. 📑 사용한 알고리즘
플로이드-워셜
모든 도시에서 다른 도시로 가는 모든 경로의 최단 거리를 구해라
그리고 N이 100밖에 안되고, 제목이 플로이드니 플로이드 워셜을 썻습니다.
3중 포문을 돌면서 dist[i][j]가 dist[i][k] + dist[k][j] 보다 크다면
즉, 경유지를 통해 가는 것이 더 거리가 짧다면 업데이트 해주는 알고리즘입니다
> (BOJ)1865웜홀 & 11404플로이드

- 제영/PGS_214288_상담원인원.java
- 제영/PGS_250134_수레움직이기.java
- 제영/제영.iml
1. 📑 사용한 알고리즘
구현
모든 경우의 수를 탐색하기 위해, 2중 for문을 사용해 파란색과 붉은색 수레를 각각 움직인다. 어떤 수레를 먼저 움직이는지는 완전탐색이기 때문에 상관이 없다.
N이 4로 작은편이라 재귀로 풀이할 수 있었습니다.
시간복잡도는 O(V^2 + E^2) 입니다.
++ 이 문제에서 주목해야 할 부분은, 서로 "스위칭"이 불가능 하다는 것 입니다.
ㅁ R ㅁ ㅁ
ㅁ B ㅁ ㅁ
ㅁ ㅁ ㅁ ㅁ
다음과 같이 빨간색 수레와 파란색 수레가 존재할 경우,
ㅁ B ㅁ ㅁ
ㅁ R ㅁ ㅁ
ㅁ ㅁ ㅁ ㅁ
다음과 같이 움직일 수는 없습니다. 당연히 한 쪽 수레가 움직이려면, 빈 공간으로 움직여야 합니다.
해당 부분을 주의해 수레를 움직이는 조건식을 작성해야 합니다. 
제 코드에서는 다음과 같은 형식으로, 새롭게 움직인 좌표와 다른 수레의 기존 좌표를 비교해 스위칭을 검사했습니다.
```java
!(bnx == rx && bny == ry && rnx == bx && rny == by)
```
한 수레의 새롭게 움직이는 좌표가 다른 수레의 기존 좌표인지를 검사할 경우,
ㅁ B R ㅁ
ㅁ ㅁ ㅁ ㅁ
ㅁ ㅁ ㅁ ㅁ
ㅁ ㅁ B R
ㅁ ㅁ ㅁ ㅁ
ㅁ ㅁ ㅁ ㅁ
다음과 같은 경우에 움직일 수 없게 되므로 정확한 답이나오지 않습니다.
1. 📑 사용한 알고리즘
최소힙, 브루트포스
최초 각 유형 당 멘토의 수는 1로 시작한다.(유형 당 1명의 멘토는 항상 있어야 하기 때문)
1. 지연시간이 발생하는 유형들마다 현재 멘토의 수에 따른 지연시간과, …
> [PGS] 250134_수레 움직이기, [PGS] 214288_상담원 인원

- 경향/q14500_테트로미노.java
- 경향/q9019_DSLR.java
1. 📑 사용한 알고리즘
- BFS
1. queue에 현재 숫자와 현재까지의 명령어를 추가
2. DSLR 각 명령어에 따라 새로운 숫자를 계산
3. 목표 숫자 B와 일치할때까지 계산하며, 일치하는 경우 해당숫자까지의 명령어 반환
> [BOJ] DSLR, 테트로미노

- 영욱/BJ_G4_1956_운동.java
- 영욱/BJ_G5_12904_A와B.java
- 영욱/BJ_G5_12919_A와B2.java
1. 📑 사용한 알고리즘
구현
S -> T로 만들 수 있느냐를 보는 문제인데
정답 문자열부터 문제에서 준 연산대로 빼면 되는 문제입니다
1. 📑 사용한 알고리즘
재귀
A와 B1과는 다르게 문자열 맨 앞 문자가 'B'라면 두 연산 모두 수행할 수 있기 때문에
재귀를 통하여 해결하였습니다.
1. 📑 사용한 알고리즘
플로이드 워셜
400^3 은 64,000,000이라 시간 통과
출발지가 안정해져 있는 최단 거리이므로 플로이드 워셜이라고 판단했습니다.
다만 사이클을 구해야 하므로 답을 출력할 때 사이클이 있는지 체크해주었습니다
> [BOJ] A와B, A와B2, 운동

- 영욱/BJ_G4_3190_뱀.java
1. 📑 사용한 알고리즘
시뮬레이션&덱
뱀의 몸이 한 칸씩 늘어나고 줄어드는 과정이 있어야 하다 보니 
리스트 맨 앞, 맨 뒤 값 입력 출력이 원활한 Deque를 생각하게 됐습니다.
그리고 시키는대로 하면 되는데.. 세세하게 틀린 점이 있다보니 오류를 많이 범하였습니다.
주의점 1. 충돌 체크하기 전 머리를 늘리고 그 머리를 큐에 넣고 충돌 검사를 했어야 했는데
이 과정이 잘못되어 디버깅에 시간이 오래 걸렸다.
주의점 2. 입력을 다 받은 후에도 계속해서 이동할 수 있다면 이동해야하기에 while문을 추가해주었다.
> [BOJ] 3190_뱀

- 영욱/BJ_G2_11780_플로이드2.java
- 영욱/BJ_G2_1766_문제집.java
1. 📑 사용한 알고리즘
플로이드 워셜 & 경로 추적
그냥 플로이드와 다른 점은 출력이 어지러운데 블로그를 참고하고 계속 문제를 보니 이해되었다.
갈 수 없는 경로일 경우(i == j일 경우) 0을 출력하고
갈 수 있다면
경로 개수 + 출발 경로 + 중간 경로 + 도착 경로
이런 방식으로 1, 1부터 5,5까지 경로를 출력하면 되는 문제이다.
스택을 사용하는 방식이 더 빠르지만
더 이해가 쉽고 직관적이고 가독성이 높은 방식으로 List에 경로를 저장하는 방식을 택하였다.
중간 경로를 거쳐서 가는 경우가 더 빠를 경우 경유지 리스트를 초기화하고 i부터 k까지의 경로
k부터 j까지의 경로를 담아주었다.
1. 📑 사용한 알고리즘
위상정렬 & 우선순위 큐
N개의 문제를 모두 풀어야 한다.  → 그래프 완전 탐색
먼저 푸는 것이 좋은 문제가 있는 문제는, 먼저 푸는 것이 좋은 문제를 반드시 먼저 풀어야 한다. → 위상 정렬
가능하면 쉬운 문제부터 풀어야 한다.  → 우선순위 큐
평범한 위상정렬과는 다르게 가능하면 쉬운 문제( 숫자가 낮은 문제 )를 먼저 풀어야 하기 때문에
그냥 큐가 아닌 우선순위 큐를 사용해야 한다.
ex)
4 2
3 2
만일 4-3-2-1의 순서로 문제를 풀게 되면 조건 1과 조건 2를 만족한다. 하지만 조건 3을 만족하지 않는다.
4보다 3을 충분히 먼저 풀 수 있기 때문이다. 따라서 조건 3을 만족하는 문제를 풀 순서는 3-1-4-2가 된다.
inDegree 1 2 3 4   input : 4 2
1
inDegree …
> [BOJ] 플로이드2&문제집

- 영욱/BJ_G2_10775_공항.java
- 영욱/BJ_G5_1916_최소비용구하기.java
1. 📑 사용한 알고리즘
다익스트라
출발지와 도착지가 주어지고 각 간선에 대한 비용이 주어지고, 간선의 최소 비용으로 도착하라했다.
바로 다익스트라가 떠올랐다.
아주 베이직한 다익스트라 문제였고 복습에 의의를 두었습니다.
1. 📑 사용한 알고리즘
Union&Find
처음에는 진짜 문제가 무슨 말인지 몰랐다. 왜 입력이 이런데 출력이 저럴까
빠른 판단으로 블로그를 찾았다( 잘한 것 같아 )
저 블로그를 보고 문제를 깨달았다
이 문제는 문제 해석과 이 문제를 보고 서로소 집합을 떠올리는게 가장 어려운 것 같다
단순히 주어진 숫자와 가장 가까우면서 큰 수에 비행기를 집어넣는 방식으로 짠다면 N^2가 나오고
N이 100,000이니 이는 시간 초과가 날게 뻔하다
대표자를 구해주는 Union&Fin에 코드를 살짝 변형해 주면 쉽게 풀 수 있는 문제였다
비행기가 들어오면 본인 숫자의 대표 숫자가 0이 아니라면
본인 대표 숫자와 본인 대표 숫자-1을 Union해 주면 되었다.
그래야 자기 숫자와 가장 가까우면서 큰 숫자에 먼저 집어 넣게 되니까
* 2
* 1 2 3 4
* 1 1 3 4
* 2
* 1 2 3 4
* 0 1 3 4 ( 여기서 2의 1은 추후에 find과정에서 어차피 0으로 바뀌게 된다 )
* 3
* 1 2 3 4
* 0 0 0 4
> BOJ 최소비용구하기 & 공항

- 민우/Boj_15824_너봄에은캡사이신이맛있단다.java
- 민우/Boj_1799_비숍.java
- 영욱/BJ_G2_15824_너봄에는캡사이신이맛있단다.java
- 영욱/BJ_G5_7569_토마토.java
1. 📑 사용한 알고리즘
수학, 조합, 분할 정복을 이용한 거듭제곱
그냥 설명하지 않겠습니다.
제목만 보고 웃겨서 풀었다가 잘못걸렸습니다.
3시간 쓴게 아까워서 그냥 올립니다.
검색 안하고 풀면 진짜 인정해드립니다.
1. 📑 사용한 알고리즘
BFS
BFS 기본인 토마토가 다른 버전이 있길래 풀어봤습니다.
크게 달라진건 없고 위, 아래가 생긴 3차원 버전이였습니다.
3차원으로 map을 만든 후 위, 아래를 따로 체크해주고
전염이 된다면 전에 있었던 자리의 +1한 값을 넣어주고 최댓값을 체크하여 몇 일이 지났는지 확인하였습니다.
> BOJ 너 봄에는 캡사이신이 맛있단다 & 토마토

- 규현/1753_최단경로/Main.java
1. 📑 사용한 알고리즘
다익스트라
다익스트라에 대한 기본적인 구현 문제입니다. 
`시작점에서 다른 모든 정점으로의 최단 경로를 구하는 프로그램을 작성하시오. ` 라는 말을 통해 사용할 알고리즘을 알 수 있었습니다. 사실 제목부터 티가 났습니다.
처음엔 V랑 E가 조금 커보여서 이게 가능한가? 라는 생각을 했었는데, 다익스트라의 시간복잡도가 `E log V`이기 때문에 30만 * log 2만 -> 30만 * 15 정도? 이기 때문에 가능했었습니다. 풀이에는 E log E라고 써놨는데, E log V라는 사실을 다시 알았네요.
풀이방식 자체에 어려운 점은 없었지만 배열 + 연결리스트 방법이 리스트 + 리스트보다 더 빠르니까 애용해주세요.
> [BOJ] 최단경로

- 지웅/BOJ16724.java
1. 📑 사용한 알고리즘
DFS
N * M 크기의 모든 칸을 탐색하고, 이동가능한 칸들의 집합 개수를 파악하는 문제로 생각했습니다. 만약 위 그림에서 (0,0)을 통해 한 집합의 전체 칸을 탐색하였을 경우에는 상관 없지만, (0, 1) 칸을 통해 집합의 일부 칸만 탐색하였을 경우를 생각하여 int 2차원 방문 배열을 통해 각 칸마다 집합의 번호를 체크해놓는 방식으로 풀이하였습니다. 예를 들어, (0,1) 칸의 탐색 이후 (0,2) 칸을 통해 탐색을 시작하였을 때, 이동하려는 칸에 집합의 번호가 체크되어있다면 (0,2) 칸을 그 집합의 번호로 체크하고 탐색을 끝냅니다.
> [BOJ] 피리부는 사나이

- 영욱/BJ_G5_11000_강의실배정_CustomReader.java
- 영욱/BJ_G5_22251_빌런호석.java
- 영욱/PG_LV2_요격시스템.java
1. 📑 사용한 알고리즘
그리디
수업 시작과 끝을 따로 클래스로 만들어 PQ로 따로 따로 만든게 핵심이였습니다.
1. 📑 사용한 알고리즘
구현
일단 각 숫자가 다른 숫자로 변환할 때 필요한 반전 개수를 미리 2차원 배열에 담았습니다.
그리고 1부터 N( num )까지 현재 숫자에서 num까지 가는데 필요한 반전 개수를 구하고
그게 P보다 낮으면 정답체크 하였습니다
더 빠른 방법이 떠오르긴 했는데 시간나면 해볼게요잉
1. 📑 사용한 알고리즘
구현
2차원 배열을 정렬한 후 현재 s가 그 전의 e보다 같거나 크면
새로운 미사일을 쏘도록 구현하였습니다
> BOJ 강의실 배정, 빌런호석 , PG 요격시스의실 배정, 빌런호석 , PG 요격시스템

- 영욱/BJ_G2_1202_보석도둑.java
1. 📑 사용한 알고리즘
자료구조, 정렬
코드 안에 상세히 적혀있습니다.
푸실 분들은 안보고 푸세요..!!
> [BOJ] 보석 도둑

- 영욱/PG_LV2_리코쳇로봇.java
- 영욱/PG_LV3_경주로건설.java
- 영욱/PG_LV3_야근지수.java
1. 📑 사용한 알고리즘
DP + BFS
처음에는 단순히 2차원 배열에 최소값을 메모이제이션해서 풀었습니다.
테케는 통과했지만 반례들이 많았고 결국 3차원 메모이제이션을 통해 해결하였습니다.
1. 📑 사용한 알고리즘
BFS
BFS이지만 한 방향으로 끝까지 가야하는 구현문제였습니다.
그렇게 끝까지 향할 때 도착지점에 도달하면 그 비용만 출력해준다면
BFS는 어차피 최단거리이기에 정답을 구할 수 있었습니다.
1. 📑 사용한 알고리즘
자료 구조 + 구현
문제만 잘 이해한다면 쉽게 풀 수 있었습니다.
결국에 제곱이라는 것은 밑을 작게할 수록 값이 작아집니다.
그래서 PQ를 사용해서 가장 밑이 큰 놈 순서대로 깎아주고 이들을 모두 제곱한 값을 더해주면 해결할 수 있습니다.
> PG 경주로건설(LV3), 리코쳇로봇(LV2), 야근지수(LV3)

- 민우/PGS_야근지수.java
1. 📑 사용한 알고리즘
그리디, 정렬
야근 피로도는 남아있는 양의 제곱이기 때문에 가장 큰값을 줄이면서 가야된다는 생각이 들었습니다. 
매번 큰값을 찾기보다는 정렬을 해두고 가장 끝값을 기준으로 lowerbound를 구해서 갯수를 찾았고, lb-1 값과의 차이만큼 빼면서 배열이 고르게 줄어들도록 했습니다.
생각보다 예외처리할게 많아서 좀 해멧네요..
> feat : add PGS 야근지수

- 규현/PGS_순위/순위.java
- 규현/PGS_정수삼각형/정수삼각형.java
1. 📑 사용한 알고리즘
BFS
권투 시합에 대한 결과가 주어졌을 때, 해당 결과를 보고 확정적으로 순위를 알 수 있는 사람의 수를 구하는 문제입니다.
승,패에 대한 결과를 가지고 그래프를 구성했고, 내가 이긴 애들에 대한 그래프, 내가 진 애들에 대한 그래프를 구성합니다.
각 선수별로, 두 그래프에 대한 bfs를 돌면서 확인할 수 있는 사람의 수가 n-1(나를 제외한 전원)이라면 순위를 확정적으로 알 수 있는 사람으로 생각하여 구현했습니다.
1. 📑 사용한 알고리즘
DP
DP에 대한 예제와 같은 문제입니다. 
아래 사진과 같이 본래 주어진 배열보다 1칸씩 더 큰 DP를 구성한 후 
dp[i+1][j+1] = origin[i][j] + max(dp[i][j], dp[i][j+1]) 식을 적용해서 풀었습니다.
> [PGS] 순위(LV3), 정수삼각형(LV3)

- 민우/PGS_기지국 설치.java
1. 📑 사용한 알고리즘
그리디
비어있는 부분을 최대크기만큼 채우기만 하면 되는 문제입니다. 기지국 설치가 안되어있는 갯수를 w의 범위로 나눠서 더하는 방식으로 풀었습니다.
3레벨이라서 풀어봤는데, 생각보다 너무 쉽네요..
> [PGS] 기지국 설치 [lv3] 

- 규현/1644_소수의_연속합/Main.java
1. 📑 사용한 알고리즘
에라토스테네스의 체, 투포인터
처음에는 소수들을 구하고 누적합을 이용한 후 주어진 N을 만드는 경우를 찾으려고 했는데, 400만 이하의 소수의 개수가 2만8천개가 넘어서 불가능하다고 생각했습니다. '연속합'이기 때문에 투 포인터를 사용해서 구한다면, 2N으로 구할 수 있기 때문에, 이 방법을 선택했습니다. 그래서 소수를 구한 후, 투 포인터로 정답을 도출했습니다.
> [BOJ] 소수의 연속합

- 규현/13023_ABCDE/Main.java
- 규현/20167_꿈틀꿈틀_호석_애벌레/Main.java
1. 📑 사용한 알고리즘
DP
모든 케이스를 계산하고, 그 중에서 Max값을 리턴하는 문제입니다.
현재 인덱스에서 애벌레가 밥을 먹는 경우 vs 안먹고 다음 인덱스로 넘어가는 경우 중에서 max 값을 dp에 저장하고, 이를 리턴했습니다.
---
1. 📑 사용한 알고리즘
그래프, DFS
문제에서 주어진 조건을 이해하는데 조금 어려웠지만, 그 외에는 어려움이 없던 문제였습니다.
A->B->C->D->E 관계를 구하기 위해서 DFS를 돌면서, 방문하지 않은 정점으로만 찍어갔고, 시작 지점부터 4개의 정점에 도착하면 성공한 것으로 취급했습니다.
> [BOJ] 꿈틀꿈틀 호석벌레 & [BOJ] ABCDE

- 규현/5052_전화번호_목록/Main.java
- 규현/SOFT_Yeah,_but_How?/Main.java
1. 📑 사용한 알고리즘
트라이
번호 A와 번호 B에 대해서 A가 B의 접두사인지를 판별하는 문제입니다. 트라이 자료구조를 이용해서 풀려고 했고, 중간 중간에 접두사인지를 판별하는 로직을 두었고, 그 과정에서 접두사 존재가 판별되면 더이상 트라이를 구성하지 않도록 하여 최적화를 해주었습니다. 그리고 다른 사람들은 트라이를 구성할 때 `Map<Character, Trie>`와 같은 형태로 작성하는데 문제에서의 인풋은 0-9까지만 나오기 때문에, 이를 배열로 처리해줘서 조금 더 이득을 봤습니다.
---
1. 📑 사용한 알고리즘
잘 모르겠음.
괄호가 주어지고 1과 +를 추가해서 올바른 식으로 만드는 문제였습니다.
올바른 식의 규칙을 찾은 뒤 StringBuilder를 통해 중간에 `1`과 `+`를 삽입해주어서 해결했습니다.
> [BOJ] 전화번호 목록 & [소프티어] Yeah, but How?

- 규현/PGS_도둑질/Solution.java
1. 📑 사용한 알고리즘
DP
문제가 집을 털어서 돈을 MAX로 훔치는 것입니다. 하지만 인접한 집은 털 수 없다는 조건이 있고, 집들이 원형으로 생겨 첫번째 집을 털면 마지막 집을 털 수 없다는 점을 유의하면 됩니다.
그래서 첫번째 집을 턴 경우와 첫 집을 털지 않는 경우에 대해서 DP를 동작하게 했습니다.
문제가 상당히 더러운게 2차원 배열을 쓰면 시간초과가 난다는 말을 들어서 1차원 배열 2개를 쓰니까 풀리더라고요.
궁금해서 아래 코드처럼 대충 테스트를 돌려봤는데 1차원 배열은 `24675905ns` 2차원 배열은 `48352266ns`로 대략 2배 차이가 난다는 점을 새로 알 수 있었습니다. 출력된 값은 저런데 제 컴퓨터가 이상한건지 2차원 배열을 할 때엔 진짜 무슨 1분정도 걸리는 느낌이어서 조금 신기하네요. 
```java
public static void main(String[] args) throws Exception {
int[][] a = new int[1_0000_0000][2];
long start = System.nanoTime();
for (int i = 0; i < 1_0000_000; i++) {
a[i][0] = 10;
a[i][1] = 20;
}
System.out.println(System.nanoTime() - start); // 48352266
//        int[] a1 = new int[1_0000_0000];
//        int[] a2 = new int[1_0000_0000];
//
//        long …
```
> [PGS] 도둑질 LV 4

- 규현/1781_컵라면/Main.java
- 규현/4519_친구_네트워크/Main.java
1. 📑 사용한 알고리즘
`정렬`, `우선순위 큐`, `그리디`
문제를 선택하는 기준을 역으로 생각했습니다. 데드라인이 가장 뒤인 날을 기준으로 가장 밸류가 높은 문제를 선택해줬습니다. 문제를 선택하면, 기준 날짜를 1씩 줄여가면서 선택가능한 문제(데드라인이 기준날짜와 동일한 문제)들을 추가해주며 밸류 높은 문제를 계속 뽑아주면서 뽑힌 문제의 컵라면 개수를 더해주면서 풀었습니다.=
---
1. 📑 사용한 알고리즘
유니온-파인드(분리 집합, Disjoint Set)
유니온 파인드를 구현해서 풀었습니다. 하지만 주어진 값이 String이기 때문에, String에 대응되는 인덱스를 만들어주기 위한 Map을 하나 만들고, 주어진 케이스(친구의 수)가 동적이기 때문에 List를 이용해서 구현해줬습니다.
> [BOJ] 컵라면 & 친구 네트워크

- 규현/1011_Fly_me_to_the_Alpha_Centauri /Main.java
- 규현/1011_Fly_me_to_the_Alpha_Centauri /Main2.java
- 규현/14442_벽_부수고_이동하기2/Main.java
1. 📑 사용한 알고리즘
`#수학`
3개의 조건이 있습니다.
```
1. 현재 속도에서 (+1,0,-1)만큼 속도를 변화하고, 그 만큼 이동할 수 있다.
2. 목적지까지 최소한의 턴을 사용해서 이동해야 한다.
3. 목적지에 도달할 때엔 속도가 1이어야 한다.
```
2번 조건을 맞추기 위해선 속도를 올릴 수 있을 때까지 올리는 것이 가장 좋다고 생각했고, 3번을 위해선 최대 속도까지 이동한 거리 (2 * Σ(n-1) + n)과 같은 식을 세워야 한다고 생각했습니다. 
설명을 편하게 하려고 `d = (2 * Σ(n-1) + n)`라고 표현하겠습니다.
본래의 거리 - `d`가 최소가 되는 `d`를 구하고, 남은 값 `e`에 대해서 `e/n`을 더하고 `e%n > 0 ? 1 : 0`을 더해주기로 생각했습니다.
그래서 `d`나 `n`을 구하는 방법을 찾아야 했는데, 수에는 규칙이 있었습니다.
| 현재 속도 | `d` | 총 사용 턴 |
|--------------|-|-|
|1 | 1 | 1|
| 2 | 4 | 3 |
| 3 | 9 | 5 |
| 4 | 16 | 7 |
| 5 | 25 | 9 |
| n | n^2 | 2*n -1|
이 규칙을 이용해서 최소한의 `d`는 본래의 이동거리의 제곱근의 제곱이라는 것을 알 수 있었습니다.
그 외의 작업은 코드를 보시면 이해할 수 있습니다.
---
`Main2.java`는 최근 봤던 코딩테스트 문제 중에서 1번과 유사한 문제에 대한 풀이입니다. 그 문제에서는 이동할 수 있는 거리 k가 1 혹은 2였는데, 1인 경우 위의 규칙을 적용하고 …
> [BOJ] Fly me to the Alpha Centauri & [BOJ] 벽 부수고 이동하기 2

- 규현/2169_로봇_조종하기/Main.java
1. 📑 사용한 알고리즘
`DP`, `DFS`
시작 좌표부터 끝 좌표까지 이동하면서 가장 많은 점수를 얻는 문제입니다. **방문한 곳을 또 가면 안된다**, **음수 좌표가 있다** 이 두 가지만 신경써주면 되는 문제였습니다. 해당 부분을 해결하기 위해 3차원 DP 배열을 만들어, 특정 좌표에 도달했을 때 어떤 방향으로 도달했느냐에 따라서 값이 달라질 수 있기 때문에, 이를 저장해줬습니다.
그 외에는 특이사항은 없습니다.
> [BOJ] 로봇 조종하기

- 민우/Boj_2957_이진탐색트리.java
1. 📑 사용한 알고리즘
이분탐색, dp(?)
일반적인 이분 탐색 트리를 구현한 후 문제를 풀게 된다면 트리의 최악의 경우의 수가 걸리는 경우 삽입에만 O(n)의 시간이 걸립니다. 이부분을 최적화 하기 위해 count 배열을 통해 몇번의 재귀를 통해 들어왔는지를 기록 후 BinarySearch를 통해 자리를 찾은 뒤 count를 부모노드 + 1로 갱신해주는 방식을 사용하여 해결했습니다.
모든 입출력이 처리되면 node를 정렬상태로 유지하기 위해 list.add(index, value ) 를 사용하여 항상 정렬된 상태를 유지하게 했습니다.
ps) 최악의 경우 1~30만까지 다 더하게 되는데 약 450억정도 되는 값이라 long타입으로 누적합을 구하셔야 합니다..
> [BOJ] 2957 이진탐색트리

- 병헌/BOJ_01283_단축키지정.java
1. 📑 사용한 알고리즘
String(?)
문제에 나온 두 가지 조건에 대해 체크하는 방식으로 진행했습니다.
첫 째로 각 단어의 초성을 보기 위해 split을 이용해 단어 별로 배열에 넣어주었고 초성이 단축키 지정이 가능한게 확인된다면 flag를 활용하여 더 이상의 불필요한 탐색을 하지 않도록 구현하였습니다.
둘 째는 첫 번째에 활용한 string 배열을 그냥 활용해서 모든 단어를 탐색했습니다. 생각해보면 굳이 그렇게 안해도 전체 string으로 돌려서 하면 for문이 더 깔끔해질 것 같다는 생각이 드네요. 
아무튼 문제가 split과 substring을 사용하면서 docs를 킬 수 밖에 없게 만들길래 머리로 풀 수 있는 사람이 있을까 하여 올립니다.
> [BOJ] 단축키지정

- 영욱/BJ_G1_13459_구슬탈출.java
- 영욱/BJ_G1_13460_구슬탈출2.java
- 영욱/BJ_G1_15644_구슬탈출3.java
- 영욱/BJ_G1_15653_구슬탈출4.java
- 영욱/BJ_G3_1937_욕심쟁이판다.java
1. 📑 사용한 알고리즘
BFS, 구현
* BFS처럼 4방향 모두 움직이는 방식으로 진행하되, 큐에 현재 시도 회수, 빨간 공 위치, 파랑 공 위치를 넣어야 함
* 1. #을 만나면 멈춘다
* 2. 빨간 공을 움직인 후 파란공을 움직인 다음 빨간 공이 계속 움직일 수 있다면 움직일 것
*  - 빨간 공을 먼저 움직일 지 파란공을 먼저 움직일 지 판별하고 움직이는 것 보다 빠르다고 판단해서 이렇게 했습니다
* 3. 움직일 때 벽, 다른 공에 도달하면 그 전에 멈추고, GOAL에 도달한다면 GOAL 위치에 멈추도록
* 4. 4차원 방문 배열을 활용해 두 빨간 공과 파란 공의 좌표에 동시에 도달한 적이 있다면 다시 볼 필요 X
64ms로 구슬 탈출 1등이니까 반박 안받겠습니다.
1. 📑 사용한 알고리즘
BFS, 구현
1과 똑같습니다. 다만 최소 시간만 리턴하면 됩니다.(어차피 1에서도 최소시간 구해야함)
1. 📑 사용한 알고리즘
BFS, 구현
움직였던 기록도 함께 저장해야 해서 클래스를 추가해줬습니다.
switch 람다방식을 적용시켜 봤습니다
1. 📑 사용한 알고리즘
BFS, 구현
10초 제한 없이 최소 값을 찾는 문제입니다
1. 📑 사용한 알고리즘
DFS, DP
* 판다는 욕심쟁이라 지금 먹은 곳보다 대나무가 더 많은 곳으로 움직인다.
* 이 문제는 dp로 현 위치에서 할 일만 잘 정해주면 풀 수 있다.
* 1. 현 …
> BOJ 구슬 탈출1,2,3,4

- 병헌/PGS_PCCP_동영상재생기.java
- 병헌/PGS_PCCP_충돌위험찾기.java
- 병헌/PGS_PCCP_퍼즐게임첼린지.java
1. 📑 사용한 알고리즘
String
아무런 알고리즘도 필요없이 그저 String에 대한 이해도와 구현 능력을 테스트하는 문제인 것 같습니다. 
String 클래스 메소드들을 활용해 아래 순서로 진행하였습니다. 
`자르기 -> 형변환 -> 구현 -> 다시 합치기`
구현 당시 헤매었던 점은 자동으로 오프닝 건너뛰기를 하는 부분이었습니다. 오프닝 시작 시점과 끝나는 시점에 따라 분기점이 너무 많이 발생해서 오래 걸렸는데 좋은 생각 있으면 제안 부탁드립니다.
1. 📑 사용한 알고리즘
Binary Search
문제를 읽은 이후 수식 하나를 계속 사용할 것 같아 작성해서 함수로 구현해주었습니다.  현재 레벨에 숙련도가 딸리면 이전 레벨과 현재 레벨에 대해서 N번 반복해주고 마지막으로 현재 레벨에 걸리는 시간을 더해주는 방식으로 작성하였습니다.
`(diffs[cur] - level) * (times[cur] + times[cur - 1]) + times[cur]`
이 후 최적의 숙련도를 찾는 방법은 전체 상황에서 가장 빠르게 탐색이 가능한 이분탐색을 적용해서 찾아내었습니다. 
1. 📑 사용한 알고리즘
BFS
문제를 제대로 읽지 않는다면 어디까지 코드가 더러워질 수 있는지 경험해볼 수 있는 좋은 문제라고 생각합니다.
우선 처음 로봇 위치를 Pos라는 클래스를 이용해 저장해주고 해당 Pos 안에 그 로봇이 움직여야하는 route를 List 형식으로 저장해주었습니다. 또한, 몇 번째 route인지 추적하기 …
> [PGS] PCCP 기출 동영상 재생기 &  퍼즐 게임 첼린지 & 충돌위험 찾기

- 병헌/PGS_WEEKLY_교점에별만들기.java
1. 📑 사용한 알고리즘
Math, HashSet
주어진 공식을 활용해서 정수 교점을 찾아내고 이를 활용해 별 찍기를 하는 문제였습니다. 
우선 정수 교점을 찾아내기 위해 처음에는 double형을 활용하고 1 모듈러 연산을 진행했을 때 0.0이 나온다면 정수 교점이라고 판단하려고 생각했습니다. 하지만 해당 방법은 주어진 테스트케이스는 통과했지만 제출 시 6점으로 평가받아 아무래도 부동소수점의 문제가 전체 결과에 영향을 미친 것으로 생각됩니다. 그래서 다시 long으로 자료형을 맞춰놓은 뒤에 분모와 분자를 각각 계산하고 분자 % 분모의 결과가 0이라면 정수로 판단하는 방식으로 바꿔서 체크했습니다. 
다음으로 좌표에 별을 찍는 부분은 x 좌표는 음수부터 시작하지만 y 좌표는 양수부터 시작하는 점 때문에 별도로 계산해주어야했습니다. 생각이 짧아 출력 시 별이 계속 거꾸로 나오는걸 보고 깨달아 고쳤던 부분이라 문제가 꽤 생각할 점이 많았던 것 같습니다. 
추가로 좌표 크기가 1000 * 1000으로 고정이어서 x, y값의 min, max값을 각각 -1001, 1001로 잡았으나 계속 메모리 초과가 떠 생각해보니 첫 좌표가 1000이고 끝 좌표가 2000이어도 해당 크기 안에 포함된다는 것을 알 수 있었습니다. 
마지막으로 HashSet을 사용하며 Pos 클래스를 새로 만들어 equals와 hashcode 오버라이드를 클래스 내 새로 해줘야 중복 비교를 해줬을 것 같은데 ide 없이 웹 에디터로 풀다보니 추가하는 법을 모르겠어서 그냥 썼읍니다. 하하 그래도 통과했으니 일단 …
> [PGS] 교점에 별 만들기

- 영욱/BJ_G3_2457_공주님의정원.java
- 영욱/BJ_G3_2638_치즈.java
1. 📑 사용한 알고리즘
BFS&구현
한 번 더 생각해야하는 BFS 문제였읍니다.
치즈가 4변 중 2변이 공기에 닿으면 지우는 것 까지는 쉬운데
이게 외부 공기인지 내부 공기인지 판별하는 걸 생각해 내는데 20분 정도 걸린 것 같습니당
1. 📑 사용한 알고리즘
그리디
아... 끝나는 달, 시간 나눠서 클래스 만들어서 하다가 머리 빠질뻔 했습니다
다른 분들은 그냥 정수 하나로 받아서 비교하세요
시작일이 작은 순으로 정렬해놓고(같다면 꽃이 지는 날이 가장 뒤인거)
꽃을 가장 적게 심도록 찾아주면 끝입니다
> BOJ 치즈, BOJ 공주님의 정원

- 병헌/BOJ_03954_BrainfuckInterpreter.java
1. 📑 사용한 알고리즘
brute force, stack
문제를 꼼꼼히 읽어봐야 합니다. 난독증 환자인지 늘 문제에서 요구하는 걸 제대로 지키지 않아 문제가 발생하네요.
각 명령어에 대해 특정 동작을 수행하는 프로그램을 만들어야하는 문제입니다. 
이를 위해 우선 명령을 수행하는 프로그램 코드를 method로 만들어놨습니다. (brainFuckProgram method)
해당 문제를 해결하기 위해서는 1. 괄호 추적 2. 루프 시점 탐색 두 가지가 중요했습니다.
1번. 괄호 추적을 위해서는 정석 방식인 stack 자료구조를 활용했습니다. 
2번. 루프 시점 탐색을 위해서는 50_000_000 시점에 도달했을 때 program input의 끝에 도달해있지 않다면 루프로 판단하도록 하고 거기서 다시 돌면서 루프가 어디서 걸리는지 탐색했습니다. 이를 위해서 루프의 시작지점을 탐색하도록 하는 코드를 작성하였습니다. 
헷갈렸던 점은 대괄호 만난 시점 동작이었습니다. 대괄호를 만났을 때 조건이 만족되면 jump 아니라면 pointer + 1이었지만 문제에도 없는 조건을 혼자 만들어 대괄호 만나면 무조건 jump부터 시켰습니다. 이 점이 아니었더라면 어려운 문제는 아니라고 생각합니다. 결론은 삽질했던 부분들 모두 문제를 제대로 안 읽어서 오래걸렸네요.
> [BOJ] brainf**k interpreter

- 이언/PGS_258707_n더하기1_카드게임.java
- 이언/PGS_258709_주사위_고르기.java
1. 📑 사용한 알고리즘
<details>
<summary>스포주의</summary>
조합 및 투포인터
</details>
n=10일 때 5개를 고르는 경우의 수: 252
5개의 주사위로 가능한 가짓수: 7776
10개의 주사위로 가능한 가짓수: 6046만
모든 조합에 모든 가짓수를 계산하면 252 * 6046만 ~= 150억으로 시간 초과
5개의 주사위로 가능한 수의 합을 미리 모두 구한다 -> 252 * 7776 ~= 196만
A의 주사위 5개가 결정되면 B의 주사위 5개가 결정되므로 여기서 A가 이기는 횟수를 빠르게 구해보자
각 주사위 조합 별로 합을 모두 구하고 정렬해두면 투포인터로 비교하며 승리 횟수를 계산할 수 있다.
</details>
1. 📑 사용한 알고리즘
<details>
<summary>스포주의</summary>
그리디
</details>
기본적으로 코인을 아끼기 위해 다음 라운드로 진행할 수 없을 경우에만 코인을 사용한다.
만약 이전 라운드에서 구매를 했어야만 짝이 맞는데 안샀다면 과거로 돌아가서 해당 카드를 샀다고 생각하고, 코인을 2개 사용한다. 
이렇게 라운드를 진행하며 더 이상 짝을 만들 수 없는 라운드를 찾는다.
어떤 라운드에 카드에는 두 종류가 있다.
1. 이미 손에 있는 카드
2. 코인을 사용해서 가져올 수 있는/있었던 모든 카드 (이전 라운드 포함)
여기서 coin개의 코인으로 몇 개의 짝을 만들 수 있는지를 매 라운드마다 계산해야 한다.
n<1000인데 쓸데없이 빠르게 구현해서 1000만이어도 …
> [PGS] 주사위 고르기 & n + 1 카드게임

- 규현/PGS_N+1카드게임.java
- 규현/PGS_주사위고르기.java
1. 📑 사용한 알고리즘
조합, 이진탐색
주사위가 10개인 상황에서 나올 수 있는 경우의 수가 `6^10 * 10C5`(대락 10^9) 여서 일반적으로 풀면 시간초과가 날 수 있다고 생각했습니다. 주사위의 경우의 수를 나눠서 고려하는 것으로 6^5 * 2로 줄였고 플레이어의 주사위 값을 상대방 주사위 값 리스트에 이진탐색을 수정해서 사용해 해당 값보다 작은 가장 뒤에 인덱스를 구했습니다. 그리고 얘가 플레이어 주사위 값이 나왔을 때 이길 수 있는 경우의 수이기 떄문에 다양한 케이스(10C5)에서 가장 이기는 수가 많은 것을 골랐습니다.
---
1. 📑 사용한 알고리즘
구현?
처음에는 BF문제인가 했는데, N이 최대 996까지 나오는 걸보니 분기타다가 시초날게 보였습니다. 이 카드가 선택되는 순서가 고정되어있기 때문에, 뭔가 계산을 통해 이루어질 수 있다고 생각했습니다. 생각해낸 아이디어로는 다음과 같습니다.
1. 페어를 만들 수 있으면 바로 만드는게 좋다. (숫자별 가중치가 따로 없으니 코인 쓸꺼면 빨리 써라)
2. 페어가 떨어지면 그때 페어를 만들어서 쓰자.
이렇게 해서 싱글인 친구들만 모아두고 페어를 만들어주자고 생각했습니다. 처음 `n/3`에 속한 애들은 1코인, 나중에 뽑을 애들은 2코인으로 계산해서 페어를 만들어주고, 페어가 필요할 때 나중에 뽑아서 페어가 된 애들에 대해서 2코인을 지불하는 식으로 라운드를 지속해나갔습니다.
> [PGS]  주사위 고르기 & N+1 카드게임

- 병헌/PGS_KAKAO_산모양타일링.java
- 병헌/PGS_KAKAO_주사위굴리기.java
1. 📑 사용한 알고리즘
Combination, BruteForce
방법이 생각이 안나 모든 조합을 전부 bruteforce  방식으로 계산하되 Hash 자료구조를 이용해 중복되는 경우의 수를 최소화 하였습니다.
nCn/2를 했을 때 n의 값이 10이 최대이기 때문에 해볼만 하다고 생각했습니다. 하지만 6면 주사위끼리의 경우의 수는 6^(2/n)이 나오고 양 쪽 경우의 수를 합하면 6 ^ n이어서 해당 부분에서만 시간을 줄이기 위해 노력했습니다.
> [PGS] 주사위굴리기
